# Generated by Django 5.2.8 on 2025-12-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_remove_course_student_coursestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='name',
        ),
    ]
