# Generated by Django 5.2.8 on 2025-12-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_remove_coursestudent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='SMS.course'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='SMS.student'),
        ),
    ]
