# Generated by Django 5.2.8 on 2025-12-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_coursestudent_course_alter_coursestudent_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
